//
// Copyright Fela Ameghino 2015-2025
//
// Distributed under the GNU General Public License v3.0. (See accompanying
// file LICENSE or copy at https://www.gnu.org/licenses/gpl-3.0.txt)
//
using Microsoft.Graphics.Canvas.Geometry;
using System;
using System.Numerics;
using Telegram.Navigation;
using Windows.UI;
using Windows.UI.Composition;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Hosting;
using Windows.UI.Xaml.Shapes;

namespace Telegram.Common
{
    public partial class ThemeShadowEx
    {
        private readonly FrameworkElement _element;
        private readonly float _translationZ;

        private DropShadowRecipe _recipe;

        public ThemeShadowEx(FrameworkElement element, float translationZ)
        {
            _element = element;
            _element.SizeChanged += OnSizeChanged;
            _element.ActualThemeChanged += OnActualThemeChanged;

            _translationZ = translationZ;

            _recipe = GetDropShadowRecipe(translationZ, _element.ActualTheme);

            Invalidate();
        }

        private void Invalidate()
        {
            UpdateShadow();
            UpdateClip();
        }

        private void OnSizeChanged(object sender, SizeChangedEventArgs e)
        {
            UpdateClip();
        }

        private void OnActualThemeChanged(FrameworkElement sender, object args)
        {
            UpdateShadow();
        }

        private void UpdateShadow()
        {
            var compositor = BootStrapper.Current.Compositor;

            var shadow = compositor.CreateDropShadow();
            shadow.BlurRadius = _recipe.DirectionalBlurRadius;
            shadow.Color = _recipe.DirectionalColor;

            var child = compositor.CreateSpriteVisual();
            child.Shadow = shadow;
            child.Size = new Vector2(0, 0);
            child.Offset = new Vector3(0, 0, _recipe.DirectionalYOffset);
            child.RelativeSizeAdjustment = Vector2.One;

            ElementCompositionPreview.SetElementChildVisual(_element, child);
        }

        private void UpdateClip()
        {
            var width = _element.ActualSize.X + _recipe.LeftInset + _recipe.RightInset;
            var height = _element.ActualSize.Y + _recipe.TopInset + _recipe.BottomInset;

            var radius = 24;

            var rect1 = CanvasGeometry.CreateRectangle(null, 0, 0, width, height);
            var elli1 = CanvasGeometry.CreateRoundedRectangle(null, _recipe.LeftInset, _recipe.TopInset, _element.ActualSize.X, _element.ActualSize.Y, radius, radius);
            var group1 = rect1.CombineWith(elli1, Matrix3x2.Identity, CanvasGeometryCombine.Exclude);

            var visual = ElementCompositionPreview.GetElementVisual(_element);
            var compositor = BootStrapper.Current.Compositor;

            visual.Clip = compositor.CreateGeometricClip(compositor.CreatePathGeometry(new CompositionPath(group1)));
        }

        // The values necessary to achieve the theme shadow look, intended to be applied to a composition drop shadow.
        struct DropShadowRecipe
        {
            // Stores the corner radiuses of the content rounded rect that's casting the shadow.
            public float RadiusX;
            public float RadiusY;

            // Drop shadows have the concept of elevation, which effectively simulates elevation that projected shadows
            // have (greater elevation = bigger shadow).
            public float Elevation;

            // There are two sets of BlurRadius/Color because we'll be creating the DropShadowVisual by combining two
            // visuals - an Ambient and a Directional visual with drop shadows.

            // Provided by design. Determines how "blurred" the DropShadow should be and how far out it extends.
            public float AmbientBlurRadius;
            public float DirectionalBlurRadius;

            // Provided by design. Shadows can have a Y offset to give the illusion that light is hitting the caster at a certain angle.
            public float AmbientYOffset;
            public float DirectionalYOffset;

            // Provided by design. The opacity of the shadow.
            public float AmbientOpacity;
            public float DirectionalOpacity;

            // The color of the drop shadow being casted. The AmbientOpacity/DirectionalOpacity is already multiplied in.
            public Color AmbientColor;
            public Color DirectionalColor;

            // How much the drop shadow should poke out from underneath the caster.
            public float LeftInset;
            public float TopInset;
            public float RightInset;
            public float BottomInset;
        }

        // The "theme" drop shadow actually consists of two drop shadows, designed to simulate shadows generated by
        // two shell-wide light sources: one ambient, and one directional.
        // These formulas were taken from the shell team implementation of the ThemeNineGridShadowBrush
        // At low elevations [2 to 16], there should not be an Ambient shadow.
        // At high elevations (> 16), there will be an Ambient shadow.
        private static DropShadowRecipe GetDropShadowRecipe(float translationZ, ElementTheme t)
        {
            DropShadowRecipe recipe = new();
            recipe.Elevation = Math.Min(64.0f, translationZ / 2);   // Clamped to a max of 64 (corresponding to Translation.Z = 128)

            if (recipe.Elevation < 2)
            {
                recipe.AmbientBlurRadius = 2.0f;

                recipe.AmbientOpacity = 0;
                recipe.DirectionalOpacity = 0;
            }
            else if (recipe.Elevation >= 2 && recipe.Elevation <= 16)
            {
                recipe.AmbientBlurRadius = 2.0f;

                // Ambient shadow won't show.
                recipe.AmbientOpacity = 0;
                if (t == ElementTheme.Light)
                {
                    recipe.DirectionalOpacity = Math.Min((recipe.Elevation / 100.0f) + 0.06f, 0.14f);   // maxes out at elevation = 8
                }
                else if (t == ElementTheme.Dark)
                {
                    recipe.DirectionalOpacity = 0.26f;
                }
            }
            else
            {
                recipe.AmbientBlurRadius = recipe.Elevation / 3;    // Translation.Z / 6, but we already divided by 2
                recipe.AmbientYOffset = 2;

                if (t == ElementTheme.Light)
                {
                    recipe.AmbientOpacity = 0.15f;
                    recipe.DirectionalOpacity = 0.19f;
                }
                else if (t == ElementTheme.Dark)
                {
                    recipe.AmbientOpacity = 0.37f;
                    recipe.DirectionalOpacity = 0.37f;
                }
            }

            recipe.AmbientColor = Color.FromArgb((byte)(recipe.AmbientOpacity * 255), 0, 0, 0);
            ;
            recipe.DirectionalBlurRadius = recipe.Elevation;
            recipe.DirectionalYOffset = recipe.Elevation * 0.5f;   // positive means shifted down
            recipe.DirectionalColor = Color.FromArgb((byte)(recipe.DirectionalOpacity * 255), 0, 0, 0);
            ;

            float maxBlurRadius = MathF.Ceiling(Math.Max(recipe.AmbientBlurRadius, recipe.DirectionalBlurRadius));
            recipe.LeftInset = maxBlurRadius;
            recipe.RightInset = maxBlurRadius;
            // If the shadow is shifted vertically, then the amount of space needed for the shadow at the top and bottom
            // depend on both the shadow's blur radius and how much it shifted. A positive offset means to shift down, so
            // subtract from the top and add to the bottom.
            recipe.TopInset = MathF.Ceiling(Math.Max(recipe.AmbientBlurRadius - recipe.AmbientYOffset, recipe.DirectionalBlurRadius - recipe.DirectionalYOffset));
            recipe.BottomInset = MathF.Ceiling(Math.Max(recipe.AmbientBlurRadius + recipe.AmbientYOffset, recipe.DirectionalBlurRadius + recipe.DirectionalYOffset));

            return recipe;
        }
    }
}
